### ISSUE TITLE
Exceptions handling 

### ISSUE THREAD

**Issue by kisst** [awslabs/cfn-python-lint#114]
Based on the documentation in the Readme, and the https://github.com/awslabs/cfn-python-lint/blob/master/test/templates/good/core/config_parameters.yaml file.

I setup this list 
```
~/git/cfn-test$ yq r my-test-stack.yaml Metadata.cfn-lint
config:
  ignore_checks:
  - E2504
  - E2507
  - E2520
  - E2523
```
where yq is mikefarah's yq, similar to jq, but still I got all the errors marked bellow.

```
~/git/cfn-test$ cfn-lint --template my-test-stack.yaml | grep ^E
E2507 IAM Policy statement key Fn::If isn't valid
E2507 IAM Policy statement missing Effect
E2507 IAM Policy statement missing Action or NotAction
E2507 IAM Policy statement missing Resource or NotResource
E2523 Only one of [VirtualName, Ebs] should be specified for Resources/FileServer/Properties/BlockDeviceMappings/1
E2504 Iops shouldn't be defined for type gp2 for Resources/FileServer/Properties/BlockDeviceMappings/0/Ebs/Iops
E2520 Parameter MasterUsername should NOT exist with SourceDBInstanceIdentifier for Resources/DB/Properties
E2520 Parameter MasterUserPassword should NOT exist with SourceDBInstanceIdentifier for Resources/DB/Properties
E2520 Parameter MasterUsername should NOT exist with DBSnapshotIdentifier for Resources/DB/Properties
E2520 Parameter MasterUserPassword should NOT exist with DBSnapshotIdentifier for Resources/DB/Properties
```

and 
```
~/git/cfn-test$ cfn-lint --version
cfn-lint 0.2.1
```

This whole list is needed only just to go around this for now https://github.com/awslabs/cfn-python-lint/issues/112

**Comment by kddejong** [comment]
Made some good progress on error #112 this weekend but still trying to flush it out and get it well tested.  

Previous:
```
yq r test/templates/bad/properties_required.yaml Metadata.cfn-lint
null
```
```
$ cfn-lint --template test/templates/bad/properties_required.yaml | grep E3012 | wc -l
      10
```

Update the template.
```
$ yq r test/templates/bad/properties_required.yaml Metadata.cfn-lint
config:
  ignore_checks:
  - E3012
  - E2541
```
```
cfn-lint --template test/templates/bad/properties_required.yaml | grep E3012 | wc -l
       0
```

I'll try to test a few more scenarios as it looks like what you are doing is correct....

**Comment by kddejong** [comment]
Also just tested this template.  https://github.com/awslabs/cfn-python-lint/blob/master/test/templates/bad/properties_ebs.yaml with this added.
```
Metadata:
  cfn-lint:
    config:
      ignore_checks:
      - E2504
```
and got  empty results. 
```
$ cfn-lint --template test/templates/bad/properties_ebs.yaml | grep 2504
$
```

I tested this in python 2 and 3 so should also be covered here.

**Comment by kisst** [comment]
Great news on the #112 !
I updated the template with all the related errors.
```
 yq r my-test-stack.yaml Metadata.cfn-lint
config:
  ignore_checks:
  - E2503
  - E2504
  - E2507
  - E2520
  - E2523
  - E3012
  - W8001
```
And for some reason it worked, however the W8001 is not related, might need a separated ticket anyway thanks for the help, I think this ticket can be closed, as the exceptions are handled as it should.
