### ISSUE TITLE
RDS DB Cluster DBSnapshotIdentifier

### ISSUE THREAD

**Issue by kddejong** [awslabs/cfn-python-lint#132]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-dbsnapshotidentifier

Going to need a special check to validate the empty string value of this.  A little hard to do with a Ref but we have to remove it from Exclusive https://github.com/awslabs/cfn-python-lint/blob/master/src/cfnlint/data/AdditionalSpecs/Exclusive.json#L56-L61

`By specifying this property, you can create a DB instance from the specified DB snapshot. If the DBSnapshotIdentifier property is an empty string or the AWS::RDS::DBInstance declaration has no DBSnapshotIdentifier property, AWS CloudFormation creates a new database. If the property contains a value (other than an empty string), AWS CloudFormation creates a database from the specified snapshot. If a snapshot with the specified name doesn't exist, AWS CloudFormation can't create the database and it rolls back the stack.`

https://github.com/awslabs/aws-cfn-lint-atom/issues/8

**Comment by cmmeyer** [comment]
Closed via #228 until we have a new RDS rule (tracked in #229 )
