### ISSUE TITLE
Support for AWS StepFunctions 

### ISSUE THREAD

**Issue by Nr18** [awslabs/cfn-python-lint#150]
Would be great if the linter also validates the `DefinitionString` of the [`AWS::StepFunctions::StateMachine`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html) resource.

The value *must* be in JSON format and the structure is the [Amazon States Language](http://docs.aws.amazon.com/step-functions/latest/dg/concepts-awl.html).

On the *AWS Developers* slack in the [#serverless](https://awsdevelopers.slack.com/archives/C6LDW0BC3/p1529528449000166) channel we discussed it briefly "Simon" stated that he has one written in python that might/can be used for this purpose.

Example(s) of other state linters:

- https://github.com/awslabs/statelint

**Comment by cmmeyer** [comment]
I notice we merged a rule for StateMachines Definitions back in August. Ok to close this Issue?

**Comment by Nr18** [comment]
Makes sense to.

**Comment by kddejong** [comment]
Its worth noting this could be better but its a start.  We can adjust and make improvements as the need arises.
