### ISSUE TITLE
Add Warning on unneeded "DependsOn" Usage

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#151]
Based on this blog post:

https://aws.amazon.com/blogs/devops/optimize-aws-cloudformation-templates/

Once  `!Ref` or `!GetAtt` is used, this implicitly ends up as a `DependsOn` under hood, meaning that adding this manually add complexity and possible errors.

I think we can consider it a "best practise" not to manually add a `DependsOn` in this case (Let CloudFormation handle it correctly automatically).

So a `WXXXX` rule seems like a nice addition

**Comment by cmmeyer** [comment]
Added with #175 (and improved with #184), closing issue.
