### ISSUE TITLE
Support for AmazonMQ

### ISSUE THREAD

**Issue by LukasMusebrink** [awslabs/cfn-python-lint#170]
Version: cfn-lint 0.3.1

AWS announced CloudFormation support of Amazon MQ in US East (N. Virginia), US East (Ohio), US West (Oregon), EU (Ireland), EU (Frankfurt), and Asia Pacific (Sydney).

Consequently, there are new resource types which are currently missing in the linter.

AWS::AmazonMQ::Broker
Dokumentation: [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-broker.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-broker.html)

AWS::AmazonMQ::Configuration
Dokumentation: [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-configuration.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-configuration.html)

News: [https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-mq-now-supports-aws-cloudformation/](https://aws.amazon.com/about-aws/whats-new/2018/06/amazon-mq-now-supports-aws-cloudformation/)

**Comment by fatbasstard** [comment]
Correctly. The Spec files that drive the linter (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) are currently a bit behind and don't contain this yet. Coming soon! 😉

**Comment by LukasMusebrink** [comment]
If I only have to create the new types here: [https://github.com/awslabs/cfn-python-lint/tree/master/src/cfnlint/data/CloudSpecs](https://github.com/awslabs/cfn-python-lint/tree/master/src/cfnlint/data/CloudSpecs)  I may add them if I find the time.

Just an idea, but since the structure is always the same there may be a way to parse all types and properties from the official documentation repository? [https://github.com/awsdocs/aws-cloudformation-user-guide/tree/master/doc_source](https://github.com/awsdocs/aws-cloudformation-user-guide/tree/master/doc_source)

**Comment by cmmeyer** [comment]
Yup -- hoping to see a new resource spec in the near future.  At that point you can manually update against it with "--update-specs" but we're usually pretty good about having a new linter version out within 24 hours.  

Ok to close this issue since this is already baked into the the process?

**Comment by LukasMusebrink** [comment]
Sure! Keep up the good work and thanks for the explanation.
