### ISSUE TITLE
Vary the error code

### ISSUE THREAD

**Issue by viraptor** [awslabs/cfn-python-lint#235]
*cfn-lint version: 0.3.3*

*Description of issue.*

Whether cfn-lint finds errors or not, it always returns exit code 0. It would be great to be able to get the pass/fail result automatically (errors exiting with code != 0) without having to look at / parse the output.

This would be great in situations like validating the stacks in CI, and it would be nice to pass it to other tools which call cfn-lint (like in https://github.com/envato/stack_master/pull/245), so they can easily figure out the result / forward the exit code.

**Comment by fatbasstard** [comment]
Hi @viraptor, 

just checked the linter at the current version and it returns status codes: `0` if nothing is found, `4` if there are warnings, `2` if there are errors. And `6` if both are present: 

https://github.com/awslabs/cfn-python-lint/blob/master/src/cfnlint/core.py#L54

**Comment by viraptor** [comment]
Hmm... I made sure to test it before reporting. But trying on the first stack I have returns the right exit code.
I'll close for now and reopen if I can reproduce this with a specific example.
