### ISSUE TITLE
smsConfiguration.externalId failed to satisfy constraint

### ISSUE THREAD

**Issue by Nr18** [awslabs/cfn-python-lint#237]
*cfn-lint version: (`cfn-lint --version`)* 
0.4.1

*Description of issue.*
`smsConfiguration.externalId ` not set is not required based on the docs cfn-lint does allow it (guess based on the docs) but the deployment fails. 

Please provide as much information as possible:
* Template linting issues:
```1 validation error detected: Value null at 'smsConfiguration.externalId' failed to satisfy constraint: Member must not be null (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXXX)```
  * Please provide a CloudFormation sample that generated the issue.

```cloudformation
UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - phone_number
      MfaConfiguration: "ON"
      SmsConfiguration:
        SnsCallerArn: !GetAtt SNSRole.Arn
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: phone_number
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: slackId
          AttributeDataType: String
          Mutable: true
```
  * If present, please add links to the (official) documentation for clarification.
    * https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-smsconfiguration.html

* Feature request:
Not sure if the validator and docs are right or the parser of CFN, cfn-lint should catch this failure or CFN should deploy it IMHO.

**Comment by kddejong** [comment]
Huh, yea we are giving you no errors based on the Spec (and documentation) so that is weird.  We will have to go back and do more digging with the teams on this one.

Spec.
```
  "AWS::Cognito::UserPool.SmsConfiguration": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-smsconfiguration.html",
      "Properties": {
        "ExternalId": {
          "Required": false,
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-smsconfiguration.html#cfn-cognito-userpool-smsconfiguration-externalid",
          "PrimitiveType": "String",
          "UpdateType": "Mutable"
        },
        "SnsCallerArn": {
          "Required": false,
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-smsconfiguration.html#cfn-cognito-userpool-smsconfiguration-snscallerarn",
          "PrimitiveType": "String",
          "UpdateType": "Mutable"
        }
      }
    },
```
Documentation says its not required either. 

@cmmeyer another one for you!

**Comment by Nr18** [comment]
🎉

**Comment by lony** [comment]
So what's the solution here? How can I get Cognito setup with SMS to work?

**Comment by jimbol** [comment]
What does the Cloud Formation config for `CognitoRoleSns` look like in this case?
