### ISSUE TITLE
E3012 - boolean - mismatch between cfn-lint & Cloudformation

### ISSUE THREAD

**Issue by mpoens** [awslabs/cfn-python-lint#260]
*cfn-lint version: (`cfn-lint --version`)*
```
cfn-lint --version
cfn-lint 0.4.2
```

*Description of issue.*
The rule
E3012 Property Resources/Subnet0/Properties/MapPublicIpOnLaunch should be of type Boolean
fires, however the supplied value is acceptable to Cloudformation, and results in CREATE_COMPLETE

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
```
        "Subnet0": {
            "Properties": {
                "AvailabilityZone": {
                    "Fn::Select": [
                        0,
                        {
                            "Fn::GetAZs": ""
                        }
                    ]
                },
                "CidrBlock": "192.168.16.0/20",
                "MapPublicIpOnLaunch": "true",
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": {
                            "Fn::Join": [
                                "-",
                                [
                                    "sites-infrastructure",
                                    {
                                        "Ref": "Stage"
                                    },
                                    "public",
                                    {
                                        "Fn::Select": [
                                            0,
                                            {
                                                "Fn::GetAZs": ""
                                            }
                                        ]
                                    }
                                ]
                            ]
                        }
                    }
                ],
                "VpcId": {
                    "Ref": "VPC"
                }
            },
            "Type": "AWS::EC2::Subnet"
        },
```
  * If present, please add links to the (official) documentation for clarification.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-mappubliciponlaunch

The template in question was created by troposphere. Since Cloudformation accepts booleans enclosed in quotes, it seems arguable that E3012 should not fire. On the other hand, perhaps there is documentation that defines boolean's cannot be enclosed in quotes? If that documentation exists it would be good to become aware of it - in that case this seems like something that should get fed back to the troposphere project for consideration.

**Comment by kddejong** [comment]
This conversation has come up a few times.  #180 

Originally we had it setup as you talked about.  Where these mistype issues were Warnings and not Errors.  However, we have ran into a few scenarios where the types are strict.  The result of that is that we have made all type checks strict.

Spec data for reference:
```
"MapPublicIpOnLaunch": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-mappubliciponlaunch",
          "PrimitiveType": "Boolean",
          "Required": false,
          "UpdateType": "Mutable"
        },
```
