### ISSUE TITLE
Unnecessary !Sub not detected

### ISSUE THREAD

**Issue by adamchainz** [awslabs/cfn-python-lint#314]
*cfn-lint version: (`cfn-lint --version`)* 0.5.0

*Description of issue.*

When refactoring code it can quite often be the situation we end up with `!Sub` applied to a string that has no substitutions, e.g. `!Sub foo`. This is less clear to read than the plain string `foo`, so it would be good to detect such cases and complain about them.

**Comment by kddejong** [comment]
Good one.  This shouldn't be hard.  Thanks!
