### ISSUE TITLE
E3002 Invalid Property Resources/CfnVpcEndPoint/Properties/VpcEndpointType

### ISSUE THREAD

**Issue by neil-cloudbi** [awslabs/cfn-python-lint#342]
*cfn-lint version: 0.7.1

*Description of issue.*

The following fails with invalid property VpcEndpointType, however it creates the resource OK if I comment out the linter:

  CfnVpcEndPoint:
    Type: AWS::EC2::VPCEndpoint
    Condition: IsDevOrProd
    Properties:
      VpcId: !FindInMap [NetworkMap, !Ref EnvironmentType, "Vpc"]
      ServiceName: "com.amazonaws.eu-west-1.cloudformation"
      VpcEndpointType: "Interface"

From the docs: 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html#cfn-ec2-vpcendpoint-vpcendpointtype

**Comment by cmmeyer** [comment]
Hey, thanks for reaching out!

There's a discrepancy in the CloudFormation resource specification for the VpcEndpoint for both VpcEndpointType and PrivateDnsEnabled that I'm working with the service team to try to address. You can track this work in #219.

I'm closing this issue as a duplicate.
