### ISSUE TITLE
Validate ManagedPolicy Description

### ISSUE THREAD

**Issue by adamchainz** [awslabs/cfn-python-lint#345]
*cfn-lint version: (`cfn-lint --version`)* 0.7.1

*Description of issue.*

A recent deployment of a template with an IAM policy failed because a newline was accidentally included in the description, and IAM doesn't like that. Got this error:

> AWS::IAM::ManagedPolicy MyPolicy CREATE_FAILED: ... 'description' failed to satisfy constraint: Member must satisfy regular expression pattern: [\p{L}\p{M}\p{Z}\p{S}\p{N}\p{P}]* ...

This also isn't documented [on CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-description) or in the [IAM API](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreatePolicy.html).

**Comment by kddejong** [comment]
I'm trying to convert this regex into something we could use.  Looks like \p{Z} is for whitespace.  What I can't tell if that also includes new lines as it looks to be a subset of this one.

**Comment by kddejong** [comment]
@cmmeyer looks like to make this easier on ourselves we should convert to the regex package.  https://pypi.org/project/regex/  it comes with easy unicode character matching and makes writing this rule a lot easier.  It looks like it can drop in replace the current 're' but it would be a new dependency.
