### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by neil-cloudbi** [awslabs/cfn-python-lint#348]
*cfn-lint version: 0.7.2

By mistake I had the !Sub in the wrong place as part of an AWS::IAM::Policy resource. It produces an error stack that concludes with:

  File "/home/dev-neil/.local/lib/python3.6/site-packages/cfnlint/decode/cfn_yaml.py", line 89, in construct_yaml_map
    if key in mapping:
TypeError: unhashable type: 'dict'

```
Resource:
  - "*"
Condition:
  "StringLike":
    !Sub "ec2:ResourceTag/Name": "packer-${EnvironmentType}*"
```

Moving the !Sub to the right place resolves everything but I thought it might be useful to know. Love the linter!

**Comment by cmmeyer** [comment]
Closing this issue with the @kddejong's PR (#349)
