### ISSUE TITLE
Extend linter with required/restricted functionality

### ISSUE THREAD

**Issue by ashemedai** [awslabs/cfn-python-lint#354]
**Enhancement / Feature request**

At our company we use a wrapper linter around cfn-lint to enforce certain properties, e.g. always require encryption in-transit and at-rest.

We recently ran into an issue where we want to restrict certain properties for our users. We might not as the platform team support this functionality with tooling or we are simply trying to protect them from themselves.

As such we wondered if this kind of functionality would be useful to include in cfn-lint.

**Comment by cmmeyer** [comment]
We've tried to keep cfn-lint as a pure linter and suggest using a separate tool for governance (cfn_nag, etc.). It would be challenging to write canned governance rules that would map to multiple use cases, but there's nothing to stop you from writing custom rules for governance.

**Comment by cmmeyer** [comment]
Hi! 

So in a reversal of what I said previously, we've finally relented. We've recently added a new "Info (I) level for governance, security and best practices rules (#389). We're looking for rules to include if you have any you could contribute.

I'm going to close this issue, but feel free to comment here or just open a PR if you have rules to add.

Thanks for the suggestion.
