### ISSUE TITLE
Feature Request: Warning if DeletionPolicy is not specified

### ISSUE THREAD

**Issue by vandmo** [awslabs/cfn-python-lint#369]
Sorry for not implementing and submitting pull request but currently have no time for that.

DeletionPolicy is not required in for example DynamoDB Table and defaults to Delete.
That is not a good default value IMHO so always setting DeletionPolicy explicitly would be a nice recommendation.

**Comment by cmmeyer** [comment]
Cool "Best Practice" style addition.  I'll label it as an enhancement

**Comment by vandmo** [comment]
Thanks :)
