### ISSUE TITLE
Please consider releasing source code to pypi

### ISSUE THREAD

**Issue by sroegner** [awslabs/cfn-python-lint#377]
*cfn-lint version: (`cfn-lint --version`)*
0.7.3
*Description of issue.*
I am using a tool that requires the sources to be deployed to pypi along with the binaries

**Comment by cmmeyer** [comment]
First time we've had this request, but not unreasonable.  I'm going to mark it as an enhancement while we look into it.

**Comment by sroegner** [comment]
Thanks, much appreciated.

**Comment by kddejong** [comment]
Should be covered with the new release (v0.8.3).  Let me know if you are still having issues.
