### ISSUE TITLE
Abnormal behaviour when parsing multiple files

### ISSUE THREAD

**Issue by Saichovsky** [awslabs/cfn-python-lint#380]
*cfn-lint version: (`cfn-lint --version`)*
0.7.3
*Description of issue.*
Multiple template file processing not working properly
* Template linting issues:
  * `cfn-lint -t foo.yaml bar.yaml` behaves different from `cfn-lint bar.yaml foo.yaml` when one of the file has linting errors. If foo.yaml has errors but bar.yaml doesn't, `cfn-lint -t foo.yaml bar.yaml` exits with a code of 0, but when you switch the position of the two parameters, it returns a 2.
* The `-t` flag... what does it REALLY do?
  * I noted that when you remove the `-t` flag, the behaviour changes again - where you previously had a code of 0 now gives an exit code of 2 and vice versa. Here's a screenshot showing this behaviour https://paste.pics/3UBLN Is this behaviour expected? If not, is the `-t` flag necessary?

Sample template files:
 * https://gist.github.com/Saichovsky/bf26a0ef96dbcbb4013509f7d9dc3dcd
 * https://gist.github.com/Saichovsky/fab09cf5d054f314ea96afbb3a42e045

**Comment by kddejong** [comment]
Sorry a little confusion on this one.  Release v0.7.4 should give you what you need.  We have been doing some parameter work, moving to support multiple files, and cleaning up a few issues related to how parameters got used.  v0.7.4 will be the first one that will support multiple files.  I just submitted the pull request to get this released to you.  I'll work to get that out today.

The version you have will take multiple files as parameters but will only lint one.  

#381

**Comment by kddejong** [comment]
Similar to #323

**Comment by cmmeyer** [comment]
I'm going to close this as a duplicate to #323 -- which we will hopefully be closing today as well with the 0.7.4 release.
