### ISSUE TITLE
E3002 Invalid Property Resources/Ec2VpcEndPoint/Properties/VpcEndpointType

### ISSUE THREAD

**Issue by neil-cloudbi** [awslabs/cfn-python-lint#388]
cfn-lint 0.7.4

Hello!

I don't recall seeing these messages previously:

E3002 Invalid Property Resources/Ec2VpcEndPoint/Properties/VpcEndpointType
network_stack_template.yaml:81:7

Example resource is:

 Ec2VpcEndPoint:
   Type: AWS::EC2::VPCEndpoint
   Condition: IsDevOrProd
   Properties:
     VpcId: !FindInMap [NetworkMap, !Ref EnvironmentType, "Vpc"]
     ServiceName: "com.amazonaws.eu-west-1.ec2"
     VpcEndpointType: "Interface"

Thanks

**Comment by kddejong** [comment]
@cmmeyer  the docs have `VpcEndpointType` and the spec has `VPCEndpointType`.  Which one is it supposed to be?
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

**Comment by cmmeyer** [comment]
Yup, this is a known issue with the resource spec currently published by the CloudFormation team that we're tracking in #219.  

I've submitted a correction to the spec and we're just waiting for it to publish -- hopefully in the October deployment.

I'm going to close this issue as a duplicate.
