### ISSUE TITLE
${aws:username} now fails

### ISSUE THREAD

**Issue by neil-cloudbi** [awslabs/cfn-python-lint#401]
*cfn-lint version: 0.8

E1029 Found an embedded parameter outside of an "Fn::Sub" at Resources/ForceMFAPolicy/Properties/PolicyDocument/Statement/3/Resource/0/arn:aws:iam::*:mfa/${aws:username}

It looks like the IAM variables are now being detected as embedded parameters in cfn-lint.

            Effect: "Allow"
            Action:
              - "iam:UploadSSHPublicKey"
            Resource: "arn:aws:iam::*:user/${aws:username}"

**Comment by kddejong** [comment]
Looking into it.  This will need a fix.
