### ISSUE TITLE
Another ${aws:username} issue

### ISSUE THREAD

**Issue by ow-krioles** [awslabs/cfn-python-lint#404]
*cfn-lint version: 0.8.1*

*Description of issue.*
Reference Issue #401 , ${aws:username} is also used in the AWS::IAM::ManagedPolicy resource type and needs the same fix.

**Comment by nimbusscale** [comment]
Looking into this it just appears that the fix isn't included in 0.8.1. I manually patched in my venv and it works against ManagedPolicy. Doesn't look to be resource type specific, but field specific. 

Not sure when they plan another release.

**Comment by kddejong** [comment]
I'll do one today.

**Comment by nimbusscale** [comment]
0.8.2 works for me.

**Comment by cmmeyer** [comment]
Great to hear! Shutting this one down.
