### ISSUE TITLE
Unknown exception from rule E3021

### ISSUE THREAD

**Issue by adamchainz** [awslabs/cfn-python-lint#421]
*cfn-lint version: (`cfn-lint --version`)* 0.8.2

*Description of issue.*

```
$ cat test.yml
AWSTemplateFormatVersion: 2010-09-09

Resources:

  GlueCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Role: myrole
      DatabaseName: mydbname
      Targets:
        S3Targets:
        - Path:
            !Sub
            - s3://${BucketName}/
            - BucketName:
                Fn::ImportValue: my-bucket-name
$ cfn-lint --regions us-east-1 --template test.yml
E0002 Unknown exception while processing rule E3021: list index out of range
test.yml:1:1

```

In addition I think the 'unknown exception' message is pretty unhelpful as the stack trace is gone. But at least I could cut my template down to this minimal example.

**Comment by cmmeyer** [comment]
Agreed. We’re obviously not catching that error well. I’ll try to reproduce when I get back to my desk.

**Comment by cmmeyer** [comment]
FYI -- This was part of a larger problem where rules were not being scoped to the correct resources (the rule throwing the error here was meant for a CloudWatch Event).  We added better error handling to THAT rule, but also corrected the logic that scopes the rules.
