### ISSUE TITLE
E3003 Property CidrBlock missing

### ISSUE THREAD

**Issue by tracphil** [awslabs/cfn-python-lint#433]
*cfn-lint version: 0.8.3*

*Description of issue.*

When using `AWS::EC2::NetworkAclEntry` for an IpV6 CIDR using `Ipv6CidrBlock` instead of `CidrBlock` (see snippet below), I get this error:

```console
E3003 Property CidrBlock missing at Resources/rNaclDefaultEntryIpv6/Properties
vpc.yml:117:5
```

Please provide as much information as possible:

* Template linting issues:

```console
  rNaclDefaultEntryIpv6:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      Ipv6CidrBlock: ::/0
      Protocol: -1
      RuleAction: deny
      RuleNumber: 2
      NetworkAclId: !GetAtt [rVpc, DefaultNetworkAcl]
```

`Ipv6CidrBlock` is a valid property.

**Comment by kddejong** [comment]
@tracphil we use the CloudFormation spec to help drive some of these rules.  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

From the spec we have this.
```
  "AWS::EC2::NetworkAclEntry": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-network-acl-entry.html",
      "Properties": {
        "CidrBlock": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-network-acl-entry.html#cfn-ec2-networkaclentry-cidrblock",
          "PrimitiveType": "String",
          "Required": true,
          "UpdateType": "Mutable"
        },
```

According to the documentation.
```
Required: Conditional. You must specify the CidrBlock or Ipv6CidrBlock property.
```

Which means this should be required False.  We have spec addendum we could use to provide a check to make sure we have at least one.  Also we have created a method to patch the spec to fix the issue in the short term.  @cmmeyer and @rjlohan for visibility.
