### ISSUE TITLE
Move logic away friom __main__.py to improve usability

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#47]
Currently there is a lot of logic implemented in `__main__.py` which is nice for CLI usage, but is not as handy when used in code.

It would improve the usability of this linter and makes it easier to integrate with other tooling if logic from this class is moved away. Focus should be on parsing the arguments, run the Rules and parse the output.

ATM the logic has to be copied into other tooling that implements this

**Comment by cmmeyer** [comment]
Considering main() is now 5 lines of actual code, I think this is as skinny as we're going to get. Closing issue.
