### ISSUE TITLE
 E0000 No JSON object could be decoded

### ISSUE THREAD

**Issue by MrBeardyDrummer** [awslabs/cfn-python-lint#472]
Version:
cfn-lint 0.9.1

Error:
Command: cfn-lint --template master.yaml
Error message: E0000 No JSON object could be decoded
master.yaml:1:1

This is occuring on Ubuntu running on Windows 10, latest version of AWSCLI, Python version 2.7.15rc1

I am new to using this setup, so excuse any missing info and please let me know what additional info you may need.

**Comment by kddejong** [comment]
Sorry for the delay in responding.  I'm trying to mimic your test environment to see what I can figure out.

**Comment by kddejong** [comment]
I was able to get a Windows Server 2016 (1709), Ubuntu, with python version 2.7.12, cfn-lint v0.9.1 working. 

What version of Ubuntu are you using 18.04 or 16.04?  Going to see what an upgrade to Python brings me.

**Comment by cmmeyer** [comment]
Hey -- 

Interesting. Any chance you can share your template? That often means the JSON in the template is malformed to the point we can't see it as valid.

Maybe run it through a JSON parser?

**Comment by MrBeardyDrummer** [comment]
Hi there,

Thank you for your replies. Interestingly, my colleague has just successfully run the command and pushed the update using the same file and the same setup. I just ran the master.yaml through a josn parser and it fails saying:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data 

So I am bewildered as to why it's worked for him and failed for me. I will continue to investigate with him and update you as soon as I can.

**Comment by kddejong** [comment]
@MrBeardyDrummer were you able to figure this out or any more insights I could take to try repeat this?

**Comment by kddejong** [comment]
Closing this from inactivity.  We can always re-open if needed.

**Comment by thbishop-intuit** [comment]
FWIW, I ran into this today using `0.26.0` of `cfn-lint` with a yaml template. It turned out to be a trailing tab char on one of the lines. I used [cfn-flip](https://github.com/awslabs/aws-cfn-template-flip) to try to convert from yaml to json while troubleshooting and it blew up with a json parse error. Hopefully this saves someone time in the future.
