### ISSUE TITLE
The extension is missing from VScode IDE 

### ISSUE THREAD

**Issue by NicholasLimWM** [awslabs/cfn-python-lint#490]
*cfn-lint version: (`cfn-lint --version`)*

*Description of issue.*

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

Is there going to be a new published extension for VScode.

**Comment by NicholasLimWM** [comment]
All right! Thanks so much for the heads up. The extension was very helpful :D

Best Regards,

Nicholas
On 28 Nov 2018, 12:29 AM +0800, kddejong <notifications@github.com>, wrote:

The plugin is available. One of our sub dependencies was affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream

We are working with Code to get everything back up.

**Comment by kddejong** [comment]
@NicholasLimWM the extension is once again available.
