### ISSUE TITLE
Update all lists of allowed values in rules based on re:Invent releases

### ISSUE THREAD

**Issue by cmmeyer** [awslabs/cfn-python-lint#497]
*cfn-lint version: (`cfn-lint --version`)*
0.9.2

*Description of issue.*
The volume of releases during re:Invent means we should do an audit of all rules that have manual lists of allowed values (EC2 instance types, Lambda environments, etc.) to reflect the new normal.

Let's keep a running list here and then break out more complicated fixes as separate issues.

- [ ] AWS::EC2::Instance types
- [x] AWS::Lambda::Function environments
- [ ] ???

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
  * If present, please add links to the (official) documentation for clarification.
* Feature request:
  * Please provide argumentation about the missing feature. Context is key!

**Comment by kddejong** [comment]
I'm not sure we have any instance checks currently.

**Comment by kddejong** [comment]
I don't think we have found any more cases that need updating.  Closing this issue.
