### ISSUE TITLE
pre-commit failing with InvalidManifestError (.pre-commit-config.yaml)

### ISSUE THREAD

**Issue by pachecoalbert** [awslabs/cfn-python-lint#501]
*cfn-lint version: (`cfn-lint --version`)* v0.9.2

*Description of issue.*
I was configuring this to run as a pre-commit hook and it kept failing with the below error.

----- BEGIN ERROR ----
An error has occurred: InvalidManifestError:
=====> /Users/albertpacheco/.cache/pre-commit/repo_r2kwuln/.pre-commit-hooks.yaml does not exist
Check the log at /Users/albertpacheco/.cache/pre-commit/pre-commit.log

------ END ERROR -----

I spent a lot of time debugging this and it turns out that the pre-commit documentation specifies and older version of cfn-pythong-lint in the ".pre-commit-config.yaml" file.  Once I updated to v0.9.2 all was well.  Here is my sample .pre-commit-config.yaml that works for me.

--- BEGIN ---

repos:
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.9.2 # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        verbose: true
        name: cfn-lint-check

--- END ---

Could you update the documentation to reflect the latest version 'rev:' or add a note so others don't run into the same issue.

Thank you,
Al

PS.  This linter is great!

**Comment by kddejong** [comment]
Thanks.  We will get this updated.

**Comment by kddejong** [comment]
Updated the documentation.
