### ISSUE TITLE
False positive E1029 for ApiGateway::Method

### ISSUE THREAD

**Issue by g-pelletier** [awslabs/cfn-python-lint#511]
*cfn-lint version:* 0.10.1

*Description of issue.* Hi,
There's an issue with the validation of template that involve AWS::ApiGateway::Method in the Properties/Integration section. When the Type parameter is set to HTTP_PROXY or HTTP, and the URI is set using stageVariables in the string, an error E1029 raises in the validation.

According to the API Gateway doc (https://docs.aws.amazon.com/apigateway/latest/developerguide/amazon-api-gateway-using-stage-variables.html), the right way to call stage variables is something along the lines of this : 'https://${stageVariables.VariableName}/'

Thus, it shouldn't raise the error as it is formatted correctly.

Thanks!

**Comment by kddejong** [comment]
Sounds like a bug.  Looking into it.  Thanks.

**Comment by g-pelletier** [comment]
From this doc : https://docs.aws.amazon.com/apigateway/latest/developerguide/aws-api-gateway-stage-variables-reference.html#stage-variables-in-mapping-templates it seems that it can be used anywhere in the template.

**Comment by kddejong** [comment]
Should be fixed with release 0.10.2
