### ISSUE TITLE
New release incoming?

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#52]
With a bunch of fixes, additional rules and features in place (or in a PR), when is a new release planned?

**Comment by kddejong** [comment]
Done.  With a lot of changes still happening I will try to do a weekly release so we don't bundle anything too large.  v0.0.10 has been released and hoping to release 0.1.0 version in the next week or two.

Let me know if you have any concerns with this approach.

**Comment by fatbasstard** [comment]
So far sounds perfect 👍 

I'll update the version in our toolkit with this version, will create issues/PR is I encounter issues. Thanx!
