### ISSUE TITLE
AWS::StepFunctions::StateMachine flagged as unsupported

### ISSUE THREAD

**Issue by g-pelletier** [awslabs/cfn-python-lint#527]
*cfn-lint version: (`cfn-lint --version`)* v0.10.2

*Description of issue.*
Hi, while running a validation of one of my template, I get the error E3001, that AWS::StepFunctions::StateMachine is invalid or unsupported in ca-central-1. After verification, it is supported, and it has been for a while.

From what I understand of the code, it just need to be added to the json of the specific region.

Thanks!

**Comment by kddejong** [comment]
@cmmeyer this is verified.  I can patch the spec but we should have an internal issue for fixing the spec.

**Comment by cmmeyer** [comment]
I'll cut an internal ticket to see what's up here.

**Comment by rjlohan** [comment]
Just curious how you folks verified that this resource type is available in CA-CENTRAL-1 ? Did you successfully provision a CFN stack into that region with this resource type?

**Comment by kddejong** [comment]
I used https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ if I have some time tonight I’ll log in and check manually. Is there any difference between service availability and CloudFormation availability in a region when that resource is already covered in us-east-1 (as an example)?

**Comment by g-pelletier** [comment]
Thanks guys. Sorry for the delay, yes, we provided a Step Machine with Step functions in our ca-central-1 infrastructure.

**Comment by kddejong** [comment]
Thanks @g-pelletier.  Tested it the long way.   CloudFormation will provision `AWS::StepFunctions::StateMachine` resources in ca-central-1.
