### ISSUE TITLE
Nesting FindInMap not supported

### ISSUE THREAD

**Issue by fatbasstard** [awslabs/cfn-python-lint#57]
Don't ask why, but we have the following CloudFormation:

```
CidrBlock: !FindInMap [!FindInMap ["Environment", !Ref "Environment", "Subnets"], "eu-west-1a", "Management"]
```

Which causes an error:
```
E1011 Map Name should be a string for Resources/XXX/Properties/CidrBlock/Fn::FindInMap
../xxx.yaml:
```
The FindInMap rule does not support recursive FindInMaps.

**Comment by kddejong** [comment]
Should work though.  Fixing shortly.  Ref and FindInMap are the documented approved functions and should work for all 3 properties for findinmap.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-findinmap.html#w2ab2c21c28c26c13
