### ISSUE TITLE
Invalid or unsupported Type AWS::SSM::MaintenanceWindowTarget for resource MaintenanceWindow in us-east-1

### ISSUE THREAD

**Issue by alytle** [awslabs/cfn-python-lint#603]
*cfn-lint version: (`cfn-lint --version`)*

cfn-lint 0.12.1

*Description of issue.*

Similar problem to https://github.com/awslabs/cfn-python-lint/issues/283 except just related to type `AWS::SSM::MaintenanceWindowTarget`. I do not see this type in the Resource Specification JSON, so I assume it's still missing from the spec.

**Comment by kddejong** [comment]
Whats weird is we had it patched until #467.  I think we thought all those came in correctly but it doesn't appear to be that case.  It also appears to be an issue with certain regions as other regions have that resource.  @cmmeyer any thoughts on this?  Should we add the patch back?

**Comment by cmmeyer** [comment]
Yeah, @alytle and I chatted about this one last night. I’m with you mthat we pulled a patch when the spec wasn’t fully right. Let me dig in on the spec side and see if it’s worth re-patching for now.

**Comment by kddejong** [comment]
Fixed release v0.13.0
