### ISSUE TITLE
Feature request: TransitGateway Resource check

### ISSUE THREAD

**Issue by avatarworf** [awslabs/cfn-python-lint#667]
*cfn-lint version: (>=0.7.2)*

*The new Cloudformation resource type: EC2::TransitGateway isn't supported by the linter.*

* Feature request:
  * This type new type has been available for a few month: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgateway.html isn't yet supported by the linter

Supportability message, may relate to a specific version of botocore dependant on the linter, but yet cfn-python-lint also has no validation of the specific attributes, from my understanding

**Comment by kddejong** [comment]
Depending on the version you are running and when it was included in the CloudFormation spec you may wish to run `cfn-lint --update-specs` to get the latest version of the spec file.  Testing with the latest version of cfn-lint (0.14.0) this resource is included.

**Comment by kddejong** [comment]
@avatarworf this fix your issue?
